spring:
  datasource:
    url: jdbc:mysql://localhost:3306/oauth?createDatabaseIfNotExist=true&useSSL=false
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
  liquibase:
    enabled: true
    contexts: default
    changeLog: classpath:/db/changelog/db.changelog-master.xml
    default-schema: oauth
  application:
    name: api-security